# Generated by Django 4.2.5 on 2023-09-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_employee_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote_date',
            new_name='date',
        ),
    ]
