# Generated by Django 4.2.5 on 2023-09-23 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_vote_date_vote_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='vote',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
