# Generated by Django 4.2.5 on 2023-09-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_menu_date_alter_vote_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
